apiVersion: v1
kind: LimitRange
metadata:
  name: dev-limit-range
  namespace: dev_ns
  labels:
    app: spring_pet_clinic
    env: dev
spec:
  limits:
    - type: Container
      default:
        cpu: 250m
        memory: 512Mi
      defaultRequest:
        cpu: 100m
        memory: 256Mi
  