apiVersion: v1
kind: ResourceQuota
metadata:
  name: dev-quota
  namespace: dev_ns
spec:
  hard:
    pods: 5
    configmaps: 4
    services: 4
    services.loadbalancers: 2
    persistentvolumeclaims: 4
    requests.cpu: "2"
    requests.memory: "2Gi"
    limits.cpu: "3"
    limits.memory: "3Gi"