apiVersion: v1
kind: Service
metadata:
  name: my-service
  namespace: dev_ns
  labels:
    app: spring_pet_clinic
spec:
  selector:
    app: spring_pet_clinic
  type: NodePort
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30001
